project:
  type: website
  resources:
    - audio
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!xtra"

website:
  title: "Neural Networks Project"
  favicon: "assets/gu-logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Landing Page
      - href: report/report.qmd
        text: Report
      - text: "Technical details"
        menu:
          - text: Data Cleaning
            href: technical-details/data-cleaning/dataclean.ipynb
          - text: Exploratory Data Analysis
            href: technical-details/eda/eda.ipynb
          - text: Neural Networks
            href: technical-details/neural-networks/main.ipynb
          - text: LLM Usage Log
            href: technical-details/llm-usage-log.qmd

format:
  html:
    theme: yeti
    bibliography: ./assets/references.bib
    csl: ./assets/nature.csl
    toc: true
